server:
  port: 8000
spring:
  profiles:
    active: euk
  application:
    name: euk-provider
# actuator 服务监控 见pom
management:
  endpoints:
    web:
      exposure:
        # *号开启所有端点 关于端点作用找文档
        include: "*"
  endpoint:
    # 可以远程关闭服务节点
    shutdown:
      enabled: true
