server:
  port: 9100
spring:
  profiles:
    active: euk
  application:
    name: user-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url: http://localhost:8090
eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7000/eureka/
ribbon:
  # 连接超时 ms
  ConnectTimeout: 1000
  # 业务超时 ms
  ReadTimeout: 2000
  # 同一台实例最大重试次数 不包括首次调用
  MaxAutoRetries: 3
  # 重试其他实例最大重试次数 不包括首次调用
  MaxAutoRetriesNextServer: 1
  # 是否所有操作都重试 POST/GET/...
  OkToRetryOnAllOperations: false
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          # SEMAPHORE:信号量
          strategy: SEMAPHORE
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
