server:
  port: 7000
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://euk1.com:7000/eureka/
  instance:
    hostname: euk1.com
    metadata-map:
      dalao: liuyao
spring:
  # spring 安全认证配置 需要引用 spring secutity包 见pom
  security:
    user:
      name: liuyao
      password: 123