server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://liuyao:123@euk1.com:7000/eureka/
#    register-with-eureka: true
#    fetch-registry: true
spring:
  application:
    name: euk-consumer