server:
  port: 9999
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuyaocool/spcld.git
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7000/eureka