server:
  port: 7100
spring:
  application:
    name: zuul-test
eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7000/eureka/
# 配置文件配置负载均衡策略 配置文件大于@Bean配置
user-consumer:
  ribbon:
    # RoundRobinRule：默认轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  endpoint:
    health:
      show-details: always
      enabled: true
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  # 前缀 localhost:7500/api/v1/user-consumer/alive 有问题
#  prefix: /api/v1
  # 带上前缀请求
#  strip-prefix: false
  # 忽略微服务
  #ignored-services:
  routes:
    # 所有/xx/**下的请求都被转发到url
    xx:
      path: /xx/**
      url: https://www.baidu.com
